export const PHASES = [
  { id: 1, title: 'Lead Novo', color: 'bg-slate-500' },
  { id: 2, title: 'Contato 1', color: 'bg-blue-400' },
  { id: 3, title: 'Contato 2', color: 'bg-blue-500' },
  { id: 4, title: 'Qualificação', color: 'bg-indigo-400' },
  { id: 5, title: 'Qualificado', color: 'bg-indigo-500' },
  { id: 6, title: 'Demo Agend.', color: 'bg-purple-500' },
  { id: 7, title: 'Demo Realiz.', color: 'bg-purple-600' },
  { id: 8, title: 'Proposta', color: 'bg-amber-500' },
  { id: 9, title: 'Negociação', color: 'bg-orange-500' },
  { id: 10, title: 'Fechamento', color: 'bg-green-500' },
]

export const COLUMNS = [
  { key: 'name', label: 'Nome Completo' },
  { key: 'email_1_value', label: 'E-mail Principal' },
  { key: 'phone_1_value', label: 'Telefone Principal' },
  { key: 'source', label: 'Origem (Source)' },
  { key: 'address_1_formatted', label: 'Endereço Formato' },
  { key: 'org_name', label: 'Organização' },
  { key: 'tags', label: 'Labels/Tags' },
  { key: 'first_name', label: 'First Name' },
  { key: 'middle_name', label: 'Middle Name' },
  { key: 'last_name', label: 'Last Name' },
  { key: 'phonetic_first_name', label: 'Phonetic First Name' },
  { key: 'phonetic_middle_name', label: 'Phonetic Middle Name' },
  { key: 'phonetic_last_name', label: 'Phonetic Last Name' },
  { key: 'name_prefix', label: 'Name Prefix' },
  { key: 'name_suffix', label: 'Name Suffix' },
  { key: 'nickname', label: 'Nickname' },
  { key: 'file_as', label: 'File As' },
  { key: 'org_title', label: 'Organization Title' },
  { key: 'org_dept', label: 'Organization Department' },
  { key: 'birthday', label: 'Birthday' },
  { key: 'notes', label: 'Notes' },
  { key: 'photo', label: 'Photo' },
  { key: 'email_1_label', label: 'E-mail 1 - Label' },
  { key: 'email_2_label', label: 'E-mail 2 - Label' },
  { key: 'email_2_value', label: 'E-mail 2 - Value' },
  { key: 'phone_1_label', label: 'Phone 1 - Label' },
  { key: 'phone_2_label', label: 'Phone 2 - Label' },
  { key: 'phone_2_value', label: 'Phone 2 - Value' },
  { key: 'phone_3_label', label: 'Phone 3 - Label' },
  { key: 'phone_3_value', label: 'Phone 3 - Value' },
  { key: 'phone_4_label', label: 'Phone 4 - Label' },
  { key: 'phone_4_value', label: 'Phone 4 - Value' },
  { key: 'address_1_label', label: 'Address 1 - Label' },
  { key: 'address_1_street', label: 'Address 1 - Street' },
  { key: 'address_1_city', label: 'Address 1 - City' },
  { key: 'address_1_po_box', label: 'Address 1 - PO Box' },
  { key: 'address_1_region', label: 'Address 1 - Region' },
  { key: 'address_1_postal_code', label: 'Address 1 - Postal Code' },
  { key: 'address_1_country', label: 'Address 1 - Country' },
  { key: 'address_1_extended', label: 'Address 1 - Extended Address' },
  { key: 'website_1_label', label: 'Website 1 - Label' },
  { key: 'website_1_value', label: 'Website 1 - Value' },
]
