export const PHASES = [
  {
    id: '1. Acolhimento',
    title: '1. Acolhimento',
    color: 'bg-blue-500',
    aliases: [
      '1. Acolhimento',
      'Novo',
      'lead',
      'Lead Novo',
      'Captura + Identificação',
      'D0 - Contato Imediato',
      'Contato Inicial',
      'contact',
      '',
    ],
  },
  {
    id: '2. Qualificação',
    title: '2. Qualificação',
    color: 'bg-cyan-500',
    aliases: ['2. Qualificação', 'Validação no CRM', 'Qualificação'],
  },
  {
    id: '3. Apresentação Consultiva',
    title: '3. Apresentação Consultiva',
    color: 'bg-teal-500',
    aliases: ['3. Apresentação Consultiva', 'Contato Personalizado'],
  },
  {
    id: '4. Sondagem Financeira',
    title: '4. Sondagem Financeira',
    color: 'bg-indigo-500',
    aliases: ['4. Sondagem Financeira', 'Mapeamento de Perfil'],
  },
  {
    id: '5. Nutrição de Interesse',
    title: '5. Nutrição de Interesse',
    color: 'bg-amber-500',
    aliases: [
      '5. Nutrição de Interesse',
      'Nutrição Automática',
      'Engajamento',
      'D1 - Follow up 1',
      'D2 - Follow up 2',
      'D3 - Follow up 3',
      'D4 - Follow up 4',
    ],
  },
  {
    id: '6. Convite de Visita',
    title: '6. Convite de Visita',
    color: 'bg-orange-500',
    aliases: [
      '6. Convite de Visita',
      'Agendamento de Visita',
      'Demo Realiz.',
      'D5 - Follow up 5',
      'D6 - Follow up 6',
      'D7 - Follow up 7',
      'D8 - Follow up 8',
      'D9 - Despedida/Nutrição',
    ],
  },
  {
    id: '7. Confirmação e Rota',
    title: '7. Confirmação e Rota',
    color: 'bg-rose-500',
    aliases: ['7. Confirmação e Rota', 'Pré-Visita'],
  },
  {
    id: '8. Feedback da Visita',
    title: '8. Feedback da Visita',
    color: 'bg-purple-500',
    aliases: ['8. Feedback da Visita', 'Pós-Visita', 'Visita'],
  },
  {
    id: '9. Proposta e Condições',
    title: '9. Proposta e Condições',
    color: 'bg-emerald-500',
    aliases: ['9. Proposta e Condições', 'Proposta e Negociação', 'Proposta'],
  },
  {
    id: '10. Pós-venda e Indicação',
    title: '10. Pós-venda e Indicação',
    color: 'bg-green-600',
    aliases: ['10. Pós-venda e Indicação', 'Fechamento e Pós-Venda', 'Fechamento', 'closed'],
  },
]

export const COLUMNS = [
  { key: 'name', label: 'Nome' },
  { key: 'phone', label: 'Telefone' },
  { key: 'email_1_value', label: 'Email' },
  { key: 'source', label: 'Origem' },
  { key: 'tags', label: 'Tags' },
]
